# CMake generated Testfile for 
# Source directory: /home/tom/repos/inkscape/testfiles
# Build directory: /home/tom/repos/inkscape/testfiles
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_actions-svg-processing "/home/tom/repos/inkscape/bin/test_actions-svg-processing")
set_tests_properties(test_actions-svg-processing PROPERTIES  ENVIRONMENT "INKSCAPE_PROFILE_DIR=/home/tom/repos/inkscape/testfiles/test_profile_dir/test_actions-svg-processing;INKSCAPE_DATADIR=/home/tom/repos/inkscape/inkscape_datadir" _BACKTRACE_TRIPLES "/home/tom/repos/inkscape/testfiles/CMakeLists.txt;118;add_test;/home/tom/repos/inkscape/testfiles/CMakeLists.txt;0;")
add_test(test_async_channel "/home/tom/repos/inkscape/bin/test_async_channel")
set_tests_properties(test_async_channel PROPERTIES  ENVIRONMENT "INKSCAPE_PROFILE_DIR=/home/tom/repos/inkscape/testfiles/test_profile_dir/test_async_channel;INKSCAPE_DATADIR=/home/tom/repos/inkscape/inkscape_datadir" _BACKTRACE_TRIPLES "/home/tom/repos/inkscape/testfiles/CMakeLists.txt;118;add_test;/home/tom/repos/inkscape/testfiles/CMakeLists.txt;0;")
add_test(test_async_funclog "/home/tom/repos/inkscape/bin/test_async_funclog")
set_tests_properties(test_async_funclog PROPERTIES  ENVIRONMENT "INKSCAPE_PROFILE_DIR=/home/tom/repos/inkscape/testfiles/test_profile_dir/test_async_funclog;INKSCAPE_DATADIR=/home/tom/repos/inkscape/inkscape_datadir" _BACKTRACE_TRIPLES "/home/tom/repos/inkscape/testfiles/CMakeLists.txt;118;add_test;/home/tom/repos/inkscape/testfiles/CMakeLists.txt;0;")
add_test(test_async_progress "/home/tom/repos/inkscape/bin/test_async_progress")
set_tests_properties(test_async_progress PROPERTIES  ENVIRONMENT "INKSCAPE_PROFILE_DIR=/home/tom/repos/inkscape/testfiles/test_profile_dir/test_async_progress;INKSCAPE_DATADIR=/home/tom/repos/inkscape/inkscape_datadir" _BACKTRACE_TRIPLES "/home/tom/repos/inkscape/testfiles/CMakeLists.txt;118;add_test;/home/tom/repos/inkscape/testfiles/CMakeLists.txt;0;")
add_test(test_uri "/home/tom/repos/inkscape/bin/test_uri")
set_tests_properties(test_uri PROPERTIES  ENVIRONMENT "INKSCAPE_PROFILE_DIR=/home/tom/repos/inkscape/testfiles/test_profile_dir/test_uri;INKSCAPE_DATADIR=/home/tom/repos/inkscape/inkscape_datadir" _BACKTRACE_TRIPLES "/home/tom/repos/inkscape/testfiles/CMakeLists.txt;118;add_test;/home/tom/repos/inkscape/testfiles/CMakeLists.txt;0;")
add_test(test_util "/home/tom/repos/inkscape/bin/test_util")
set_tests_properties(test_util PROPERTIES  ENVIRONMENT "INKSCAPE_PROFILE_DIR=/home/tom/repos/inkscape/testfiles/test_profile_dir/test_util;INKSCAPE_DATADIR=/home/tom/repos/inkscape/inkscape_datadir" _BACKTRACE_TRIPLES "/home/tom/repos/inkscape/testfiles/CMakeLists.txt;118;add_test;/home/tom/repos/inkscape/testfiles/CMakeLists.txt;0;")
add_test(test_drag-and-drop-svgz "/home/tom/repos/inkscape/bin/test_drag-and-drop-svgz")
set_tests_properties(test_drag-and-drop-svgz PROPERTIES  ENVIRONMENT "INKSCAPE_PROFILE_DIR=/home/tom/repos/inkscape/testfiles/test_profile_dir/test_drag-and-drop-svgz;INKSCAPE_DATADIR=/home/tom/repos/inkscape/inkscape_datadir" _BACKTRACE_TRIPLES "/home/tom/repos/inkscape/testfiles/CMakeLists.txt;118;add_test;/home/tom/repos/inkscape/testfiles/CMakeLists.txt;0;")
add_test(test_drawing-pattern "/home/tom/repos/inkscape/bin/test_drawing-pattern")
set_tests_properties(test_drawing-pattern PROPERTIES  ENVIRONMENT "INKSCAPE_PROFILE_DIR=/home/tom/repos/inkscape/testfiles/test_profile_dir/test_drawing-pattern;INKSCAPE_DATADIR=/home/tom/repos/inkscape/inkscape_datadir" _BACKTRACE_TRIPLES "/home/tom/repos/inkscape/testfiles/CMakeLists.txt;118;add_test;/home/tom/repos/inkscape/testfiles/CMakeLists.txt;0;")
add_test(test_extract-uri "/home/tom/repos/inkscape/bin/test_extract-uri")
set_tests_properties(test_extract-uri PROPERTIES  ENVIRONMENT "INKSCAPE_PROFILE_DIR=/home/tom/repos/inkscape/testfiles/test_profile_dir/test_extract-uri;INKSCAPE_DATADIR=/home/tom/repos/inkscape/inkscape_datadir" _BACKTRACE_TRIPLES "/home/tom/repos/inkscape/testfiles/CMakeLists.txt;118;add_test;/home/tom/repos/inkscape/testfiles/CMakeLists.txt;0;")
add_test(test_attributes "/home/tom/repos/inkscape/bin/test_attributes")
set_tests_properties(test_attributes PROPERTIES  ENVIRONMENT "INKSCAPE_PROFILE_DIR=/home/tom/repos/inkscape/testfiles/test_profile_dir/test_attributes;INKSCAPE_DATADIR=/home/tom/repos/inkscape/inkscape_datadir" _BACKTRACE_TRIPLES "/home/tom/repos/inkscape/testfiles/CMakeLists.txt;118;add_test;/home/tom/repos/inkscape/testfiles/CMakeLists.txt;0;")
add_test(test_color-profile "/home/tom/repos/inkscape/bin/test_color-profile")
set_tests_properties(test_color-profile PROPERTIES  ENVIRONMENT "INKSCAPE_PROFILE_DIR=/home/tom/repos/inkscape/testfiles/test_profile_dir/test_color-profile;INKSCAPE_DATADIR=/home/tom/repos/inkscape/inkscape_datadir" _BACKTRACE_TRIPLES "/home/tom/repos/inkscape/testfiles/CMakeLists.txt;118;add_test;/home/tom/repos/inkscape/testfiles/CMakeLists.txt;0;")
add_test(test_dir-util "/home/tom/repos/inkscape/bin/test_dir-util")
set_tests_properties(test_dir-util PROPERTIES  ENVIRONMENT "INKSCAPE_PROFILE_DIR=/home/tom/repos/inkscape/testfiles/test_profile_dir/test_dir-util;INKSCAPE_DATADIR=/home/tom/repos/inkscape/inkscape_datadir" _BACKTRACE_TRIPLES "/home/tom/repos/inkscape/testfiles/CMakeLists.txt;118;add_test;/home/tom/repos/inkscape/testfiles/CMakeLists.txt;0;")
add_test(test_oklab-color "/home/tom/repos/inkscape/bin/test_oklab-color")
set_tests_properties(test_oklab-color PROPERTIES  ENVIRONMENT "INKSCAPE_PROFILE_DIR=/home/tom/repos/inkscape/testfiles/test_profile_dir/test_oklab-color;INKSCAPE_DATADIR=/home/tom/repos/inkscape/inkscape_datadir" _BACKTRACE_TRIPLES "/home/tom/repos/inkscape/testfiles/CMakeLists.txt;118;add_test;/home/tom/repos/inkscape/testfiles/CMakeLists.txt;0;")
add_test(test_sp-object "/home/tom/repos/inkscape/bin/test_sp-object")
set_tests_properties(test_sp-object PROPERTIES  ENVIRONMENT "INKSCAPE_PROFILE_DIR=/home/tom/repos/inkscape/testfiles/test_profile_dir/test_sp-object;INKSCAPE_DATADIR=/home/tom/repos/inkscape/inkscape_datadir" _BACKTRACE_TRIPLES "/home/tom/repos/inkscape/testfiles/CMakeLists.txt;118;add_test;/home/tom/repos/inkscape/testfiles/CMakeLists.txt;0;")
add_test(test_sp-object-tags "/home/tom/repos/inkscape/bin/test_sp-object-tags")
set_tests_properties(test_sp-object-tags PROPERTIES  ENVIRONMENT "INKSCAPE_PROFILE_DIR=/home/tom/repos/inkscape/testfiles/test_profile_dir/test_sp-object-tags;INKSCAPE_DATADIR=/home/tom/repos/inkscape/inkscape_datadir" _BACKTRACE_TRIPLES "/home/tom/repos/inkscape/testfiles/CMakeLists.txt;118;add_test;/home/tom/repos/inkscape/testfiles/CMakeLists.txt;0;")
add_test(test_object-links "/home/tom/repos/inkscape/bin/test_object-links")
set_tests_properties(test_object-links PROPERTIES  ENVIRONMENT "INKSCAPE_PROFILE_DIR=/home/tom/repos/inkscape/testfiles/test_profile_dir/test_object-links;INKSCAPE_DATADIR=/home/tom/repos/inkscape/inkscape_datadir" _BACKTRACE_TRIPLES "/home/tom/repos/inkscape/testfiles/CMakeLists.txt;118;add_test;/home/tom/repos/inkscape/testfiles/CMakeLists.txt;0;")
add_test(test_object-set "/home/tom/repos/inkscape/bin/test_object-set")
set_tests_properties(test_object-set PROPERTIES  ENVIRONMENT "INKSCAPE_PROFILE_DIR=/home/tom/repos/inkscape/testfiles/test_profile_dir/test_object-set;INKSCAPE_DATADIR=/home/tom/repos/inkscape/inkscape_datadir" _BACKTRACE_TRIPLES "/home/tom/repos/inkscape/testfiles/CMakeLists.txt;118;add_test;/home/tom/repos/inkscape/testfiles/CMakeLists.txt;0;")
add_test(test_object-style "/home/tom/repos/inkscape/bin/test_object-style")
set_tests_properties(test_object-style PROPERTIES  ENVIRONMENT "INKSCAPE_PROFILE_DIR=/home/tom/repos/inkscape/testfiles/test_profile_dir/test_object-style;INKSCAPE_DATADIR=/home/tom/repos/inkscape/inkscape_datadir" _BACKTRACE_TRIPLES "/home/tom/repos/inkscape/testfiles/CMakeLists.txt;118;add_test;/home/tom/repos/inkscape/testfiles/CMakeLists.txt;0;")
add_test(test_path-boolop "/home/tom/repos/inkscape/bin/test_path-boolop")
set_tests_properties(test_path-boolop PROPERTIES  ENVIRONMENT "INKSCAPE_PROFILE_DIR=/home/tom/repos/inkscape/testfiles/test_profile_dir/test_path-boolop;INKSCAPE_DATADIR=/home/tom/repos/inkscape/inkscape_datadir" _BACKTRACE_TRIPLES "/home/tom/repos/inkscape/testfiles/CMakeLists.txt;118;add_test;/home/tom/repos/inkscape/testfiles/CMakeLists.txt;0;")
add_test(test_path-reverse-lpe "/home/tom/repos/inkscape/bin/test_path-reverse-lpe")
set_tests_properties(test_path-reverse-lpe PROPERTIES  ENVIRONMENT "INKSCAPE_PROFILE_DIR=/home/tom/repos/inkscape/testfiles/test_profile_dir/test_path-reverse-lpe;INKSCAPE_DATADIR=/home/tom/repos/inkscape/inkscape_datadir" _BACKTRACE_TRIPLES "/home/tom/repos/inkscape/testfiles/CMakeLists.txt;118;add_test;/home/tom/repos/inkscape/testfiles/CMakeLists.txt;0;")
add_test(test_preferences "/home/tom/repos/inkscape/bin/test_preferences")
set_tests_properties(test_preferences PROPERTIES  ENVIRONMENT "INKSCAPE_PROFILE_DIR=/home/tom/repos/inkscape/testfiles/test_profile_dir/test_preferences;INKSCAPE_DATADIR=/home/tom/repos/inkscape/inkscape_datadir" _BACKTRACE_TRIPLES "/home/tom/repos/inkscape/testfiles/CMakeLists.txt;118;add_test;/home/tom/repos/inkscape/testfiles/CMakeLists.txt;0;")
add_test(test_rebase-hrefs "/home/tom/repos/inkscape/bin/test_rebase-hrefs")
set_tests_properties(test_rebase-hrefs PROPERTIES  ENVIRONMENT "INKSCAPE_PROFILE_DIR=/home/tom/repos/inkscape/testfiles/test_profile_dir/test_rebase-hrefs;INKSCAPE_DATADIR=/home/tom/repos/inkscape/inkscape_datadir" _BACKTRACE_TRIPLES "/home/tom/repos/inkscape/testfiles/CMakeLists.txt;118;add_test;/home/tom/repos/inkscape/testfiles/CMakeLists.txt;0;")
add_test(test_stream "/home/tom/repos/inkscape/bin/test_stream")
set_tests_properties(test_stream PROPERTIES  ENVIRONMENT "INKSCAPE_PROFILE_DIR=/home/tom/repos/inkscape/testfiles/test_profile_dir/test_stream;INKSCAPE_DATADIR=/home/tom/repos/inkscape/inkscape_datadir" _BACKTRACE_TRIPLES "/home/tom/repos/inkscape/testfiles/CMakeLists.txt;118;add_test;/home/tom/repos/inkscape/testfiles/CMakeLists.txt;0;")
add_test(test_style-elem "/home/tom/repos/inkscape/bin/test_style-elem")
set_tests_properties(test_style-elem PROPERTIES  ENVIRONMENT "INKSCAPE_PROFILE_DIR=/home/tom/repos/inkscape/testfiles/test_profile_dir/test_style-elem;INKSCAPE_DATADIR=/home/tom/repos/inkscape/inkscape_datadir" _BACKTRACE_TRIPLES "/home/tom/repos/inkscape/testfiles/CMakeLists.txt;118;add_test;/home/tom/repos/inkscape/testfiles/CMakeLists.txt;0;")
add_test(test_style-internal "/home/tom/repos/inkscape/bin/test_style-internal")
set_tests_properties(test_style-internal PROPERTIES  ENVIRONMENT "INKSCAPE_PROFILE_DIR=/home/tom/repos/inkscape/testfiles/test_profile_dir/test_style-internal;INKSCAPE_DATADIR=/home/tom/repos/inkscape/inkscape_datadir" _BACKTRACE_TRIPLES "/home/tom/repos/inkscape/testfiles/CMakeLists.txt;118;add_test;/home/tom/repos/inkscape/testfiles/CMakeLists.txt;0;")
add_test(test_style "/home/tom/repos/inkscape/bin/test_style")
set_tests_properties(test_style PROPERTIES  ENVIRONMENT "INKSCAPE_PROFILE_DIR=/home/tom/repos/inkscape/testfiles/test_profile_dir/test_style;INKSCAPE_DATADIR=/home/tom/repos/inkscape/inkscape_datadir" _BACKTRACE_TRIPLES "/home/tom/repos/inkscape/testfiles/CMakeLists.txt;118;add_test;/home/tom/repos/inkscape/testfiles/CMakeLists.txt;0;")
add_test(test_svg-affine "/home/tom/repos/inkscape/bin/test_svg-affine")
set_tests_properties(test_svg-affine PROPERTIES  ENVIRONMENT "INKSCAPE_PROFILE_DIR=/home/tom/repos/inkscape/testfiles/test_profile_dir/test_svg-affine;INKSCAPE_DATADIR=/home/tom/repos/inkscape/inkscape_datadir" _BACKTRACE_TRIPLES "/home/tom/repos/inkscape/testfiles/CMakeLists.txt;118;add_test;/home/tom/repos/inkscape/testfiles/CMakeLists.txt;0;")
add_test(test_svg-box "/home/tom/repos/inkscape/bin/test_svg-box")
set_tests_properties(test_svg-box PROPERTIES  ENVIRONMENT "INKSCAPE_PROFILE_DIR=/home/tom/repos/inkscape/testfiles/test_profile_dir/test_svg-box;INKSCAPE_DATADIR=/home/tom/repos/inkscape/inkscape_datadir" _BACKTRACE_TRIPLES "/home/tom/repos/inkscape/testfiles/CMakeLists.txt;118;add_test;/home/tom/repos/inkscape/testfiles/CMakeLists.txt;0;")
add_test(test_svg-color "/home/tom/repos/inkscape/bin/test_svg-color")
set_tests_properties(test_svg-color PROPERTIES  ENVIRONMENT "INKSCAPE_PROFILE_DIR=/home/tom/repos/inkscape/testfiles/test_profile_dir/test_svg-color;INKSCAPE_DATADIR=/home/tom/repos/inkscape/inkscape_datadir" _BACKTRACE_TRIPLES "/home/tom/repos/inkscape/testfiles/CMakeLists.txt;118;add_test;/home/tom/repos/inkscape/testfiles/CMakeLists.txt;0;")
add_test(test_svg-length "/home/tom/repos/inkscape/bin/test_svg-length")
set_tests_properties(test_svg-length PROPERTIES  ENVIRONMENT "INKSCAPE_PROFILE_DIR=/home/tom/repos/inkscape/testfiles/test_profile_dir/test_svg-length;INKSCAPE_DATADIR=/home/tom/repos/inkscape/inkscape_datadir" _BACKTRACE_TRIPLES "/home/tom/repos/inkscape/testfiles/CMakeLists.txt;118;add_test;/home/tom/repos/inkscape/testfiles/CMakeLists.txt;0;")
add_test(test_svg-stringstream "/home/tom/repos/inkscape/bin/test_svg-stringstream")
set_tests_properties(test_svg-stringstream PROPERTIES  ENVIRONMENT "INKSCAPE_PROFILE_DIR=/home/tom/repos/inkscape/testfiles/test_profile_dir/test_svg-stringstream;INKSCAPE_DATADIR=/home/tom/repos/inkscape/inkscape_datadir" _BACKTRACE_TRIPLES "/home/tom/repos/inkscape/testfiles/CMakeLists.txt;118;add_test;/home/tom/repos/inkscape/testfiles/CMakeLists.txt;0;")
add_test(test_sp-gradient "/home/tom/repos/inkscape/bin/test_sp-gradient")
set_tests_properties(test_sp-gradient PROPERTIES  ENVIRONMENT "INKSCAPE_PROFILE_DIR=/home/tom/repos/inkscape/testfiles/test_profile_dir/test_sp-gradient;INKSCAPE_DATADIR=/home/tom/repos/inkscape/inkscape_datadir" _BACKTRACE_TRIPLES "/home/tom/repos/inkscape/testfiles/CMakeLists.txt;118;add_test;/home/tom/repos/inkscape/testfiles/CMakeLists.txt;0;")
add_test(test_svg-path-geom "/home/tom/repos/inkscape/bin/test_svg-path-geom")
set_tests_properties(test_svg-path-geom PROPERTIES  ENVIRONMENT "INKSCAPE_PROFILE_DIR=/home/tom/repos/inkscape/testfiles/test_profile_dir/test_svg-path-geom;INKSCAPE_DATADIR=/home/tom/repos/inkscape/inkscape_datadir" _BACKTRACE_TRIPLES "/home/tom/repos/inkscape/testfiles/CMakeLists.txt;118;add_test;/home/tom/repos/inkscape/testfiles/CMakeLists.txt;0;")
add_test(test_visual-bounds "/home/tom/repos/inkscape/bin/test_visual-bounds")
set_tests_properties(test_visual-bounds PROPERTIES  ENVIRONMENT "INKSCAPE_PROFILE_DIR=/home/tom/repos/inkscape/testfiles/test_profile_dir/test_visual-bounds;INKSCAPE_DATADIR=/home/tom/repos/inkscape/inkscape_datadir" _BACKTRACE_TRIPLES "/home/tom/repos/inkscape/testfiles/CMakeLists.txt;118;add_test;/home/tom/repos/inkscape/testfiles/CMakeLists.txt;0;")
add_test(test_geom-pathstroke "/home/tom/repos/inkscape/bin/test_geom-pathstroke")
set_tests_properties(test_geom-pathstroke PROPERTIES  ENVIRONMENT "INKSCAPE_PROFILE_DIR=/home/tom/repos/inkscape/testfiles/test_profile_dir/test_geom-pathstroke;INKSCAPE_DATADIR=/home/tom/repos/inkscape/inkscape_datadir" _BACKTRACE_TRIPLES "/home/tom/repos/inkscape/testfiles/CMakeLists.txt;118;add_test;/home/tom/repos/inkscape/testfiles/CMakeLists.txt;0;")
add_test(test_livarot-pathoutline "/home/tom/repos/inkscape/bin/test_livarot-pathoutline")
set_tests_properties(test_livarot-pathoutline PROPERTIES  ENVIRONMENT "INKSCAPE_PROFILE_DIR=/home/tom/repos/inkscape/testfiles/test_profile_dir/test_livarot-pathoutline;INKSCAPE_DATADIR=/home/tom/repos/inkscape/inkscape_datadir" _BACKTRACE_TRIPLES "/home/tom/repos/inkscape/testfiles/CMakeLists.txt;118;add_test;/home/tom/repos/inkscape/testfiles/CMakeLists.txt;0;")
add_test(test_object "/home/tom/repos/inkscape/bin/test_object")
set_tests_properties(test_object PROPERTIES  ENVIRONMENT "INKSCAPE_PROFILE_DIR=/home/tom/repos/inkscape/testfiles/test_profile_dir/test_object;INKSCAPE_DATADIR=/home/tom/repos/inkscape/inkscape_datadir" _BACKTRACE_TRIPLES "/home/tom/repos/inkscape/testfiles/CMakeLists.txt;118;add_test;/home/tom/repos/inkscape/testfiles/CMakeLists.txt;0;")
add_test(test_sp-glyph-kerning "/home/tom/repos/inkscape/bin/test_sp-glyph-kerning")
set_tests_properties(test_sp-glyph-kerning PROPERTIES  ENVIRONMENT "INKSCAPE_PROFILE_DIR=/home/tom/repos/inkscape/testfiles/test_profile_dir/test_sp-glyph-kerning;INKSCAPE_DATADIR=/home/tom/repos/inkscape/inkscape_datadir" _BACKTRACE_TRIPLES "/home/tom/repos/inkscape/testfiles/CMakeLists.txt;118;add_test;/home/tom/repos/inkscape/testfiles/CMakeLists.txt;0;")
add_test(test_cairo-utils "/home/tom/repos/inkscape/bin/test_cairo-utils")
set_tests_properties(test_cairo-utils PROPERTIES  ENVIRONMENT "INKSCAPE_PROFILE_DIR=/home/tom/repos/inkscape/testfiles/test_profile_dir/test_cairo-utils;INKSCAPE_DATADIR=/home/tom/repos/inkscape/inkscape_datadir" _BACKTRACE_TRIPLES "/home/tom/repos/inkscape/testfiles/CMakeLists.txt;118;add_test;/home/tom/repos/inkscape/testfiles/CMakeLists.txt;0;")
add_test(test_svg-extension "/home/tom/repos/inkscape/bin/test_svg-extension")
set_tests_properties(test_svg-extension PROPERTIES  ENVIRONMENT "INKSCAPE_PROFILE_DIR=/home/tom/repos/inkscape/testfiles/test_profile_dir/test_svg-extension;INKSCAPE_DATADIR=/home/tom/repos/inkscape/inkscape_datadir" _BACKTRACE_TRIPLES "/home/tom/repos/inkscape/testfiles/CMakeLists.txt;118;add_test;/home/tom/repos/inkscape/testfiles/CMakeLists.txt;0;")
add_test(test_curve "/home/tom/repos/inkscape/bin/test_curve")
set_tests_properties(test_curve PROPERTIES  ENVIRONMENT "INKSCAPE_PROFILE_DIR=/home/tom/repos/inkscape/testfiles/test_profile_dir/test_curve;INKSCAPE_DATADIR=/home/tom/repos/inkscape/inkscape_datadir" _BACKTRACE_TRIPLES "/home/tom/repos/inkscape/testfiles/CMakeLists.txt;118;add_test;/home/tom/repos/inkscape/testfiles/CMakeLists.txt;0;")
add_test(test_2geom-characterization "/home/tom/repos/inkscape/bin/test_2geom-characterization")
set_tests_properties(test_2geom-characterization PROPERTIES  ENVIRONMENT "INKSCAPE_PROFILE_DIR=/home/tom/repos/inkscape/testfiles/test_profile_dir/test_2geom-characterization;INKSCAPE_DATADIR=/home/tom/repos/inkscape/inkscape_datadir" _BACKTRACE_TRIPLES "/home/tom/repos/inkscape/testfiles/CMakeLists.txt;118;add_test;/home/tom/repos/inkscape/testfiles/CMakeLists.txt;0;")
add_test(test_xml "/home/tom/repos/inkscape/bin/test_xml")
set_tests_properties(test_xml PROPERTIES  ENVIRONMENT "INKSCAPE_PROFILE_DIR=/home/tom/repos/inkscape/testfiles/test_profile_dir/test_xml;INKSCAPE_DATADIR=/home/tom/repos/inkscape/inkscape_datadir" _BACKTRACE_TRIPLES "/home/tom/repos/inkscape/testfiles/CMakeLists.txt;118;add_test;/home/tom/repos/inkscape/testfiles/CMakeLists.txt;0;")
add_test(test_sp-item-group "/home/tom/repos/inkscape/bin/test_sp-item-group")
set_tests_properties(test_sp-item-group PROPERTIES  ENVIRONMENT "INKSCAPE_PROFILE_DIR=/home/tom/repos/inkscape/testfiles/test_profile_dir/test_sp-item-group;INKSCAPE_DATADIR=/home/tom/repos/inkscape/inkscape_datadir" _BACKTRACE_TRIPLES "/home/tom/repos/inkscape/testfiles/CMakeLists.txt;118;add_test;/home/tom/repos/inkscape/testfiles/CMakeLists.txt;0;")
add_test(test_lpe "/home/tom/repos/inkscape/bin/test_lpe")
set_tests_properties(test_lpe PROPERTIES  ENVIRONMENT "INKSCAPE_PROFILE_DIR=/home/tom/repos/inkscape/testfiles/test_profile_dir/test_lpe;INKSCAPE_DATADIR=/home/tom/repos/inkscape/inkscape_datadir" _BACKTRACE_TRIPLES "/home/tom/repos/inkscape/testfiles/CMakeLists.txt;118;add_test;/home/tom/repos/inkscape/testfiles/CMakeLists.txt;0;")
add_test(test_lpe64 "/home/tom/repos/inkscape/bin/test_lpe64")
set_tests_properties(test_lpe64 PROPERTIES  ENVIRONMENT "INKSCAPE_PROFILE_DIR=/home/tom/repos/inkscape/testfiles/test_profile_dir/test_lpe64;INKSCAPE_DATADIR=/home/tom/repos/inkscape/inkscape_datadir" _BACKTRACE_TRIPLES "/home/tom/repos/inkscape/testfiles/CMakeLists.txt;118;add_test;/home/tom/repos/inkscape/testfiles/CMakeLists.txt;0;")
subdirs("cli_tests")
subdirs("rendering_tests")
subdirs("lpe_tests")
